/*
- Date/Time (for 10 minutes intervals)
- LV ActivePower (kW): The power generated by the turbine for that moment
- Wind Speed (m/s): The wind speed at the hub height of the turbine (the wind speed that turbine use for electricity generation)
- Theoretical_Power_Curve (KWh): The theoretical power values that the turbine generates with that wind speed which is given by the turbine manufacturer
- Wind Direction (°): The wind direction at the hub height of the turbine (wind turbines turn to this direction automaticly)
*/
-- create windturbine table
CREATE TABLE IF NOT EXISTS windturbine (
    id SERIAL PRIMARY KEY,
    date_time timestamp NOT NULL,
    lv_active_power DOUBLE PRECISION NOT NULL,
    wind_speed DOUBLE PRECISION NOT NULL,
    theoretical_power_curve SMALLINT NOT NULL,
    wind_direction DOUBLE PRECISION NOT NULL
);
